name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy-gh-pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install plantuml fonts-noto-cjk
      - run: make
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
