name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gh-pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install plantuml
      - run: make render
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' }}
        with:
          publish_dir: ./dist
